version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: literAlura
    restart: always
    environment:
      POSTGRES_USER: facualura
      POSTGRES_PASSWORD: facualura
      POSTGRES_DB: LiterAlura
    ports:
      - "5444:5432"
    volumes:
      - ./postgres:/var/lib/postgesql/data